<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="1" verbose="2" name="Failed suite [TestNG Forum]" parallel="classes">
  <parameter name="device" value=""/>
  <listeners>
    <listener class-name="com.appium.manager.AppiumParallelTest"/>
    <listener class-name="com.appium.utils.RetryListener"/>
  </listeners>
  <test name="TestNG Test">
    <parameter name="device" value=""/>
    <classes>
      <class name="Tests.LoginTest"/>
    </classes>
  </test> <!-- TestNG Test -->
  <test name="TestNG Test(failed)" parallel="classes">
    <parameter name="device" value=""/>
    <classes>
      <class name="Tests.LoginTest">
        <methods>
          <include name="testpositive1"/>
          <include name="startAppiumServer"/>
          <include name="beforeClass"/>
          <include name="killAppiumServer"/>
          <include name="startApp"/>
          <include name="testpositive"/>
          <include name="killServer"/>
        </methods>
      </class> <!-- Tests.LoginTest -->
    </classes>
  </test> <!-- TestNG Test(failed) -->
</suite> <!-- Failed suite [TestNG Forum] -->
